### ISSUE TITLE
Checksum failure in Firefox

### ISSUE THREAD

**Issue by akashlevy** [eladkarako/hosts.eladkarako.com#1]
When using hosts-adblock.txt, I get "checksum failed" in Firefox. Any idea why this might be happening?

**Comment by eladkarako** [comment]
hmm.. 
any chance you can tell how long it happens? started today yesterday?

<sub>p.s.</sub>
<sub>avoid using <code>hosts-adblock.txt</code> if you can copy <code>hosts0.txt</code>'s content to the end of your computer's HOSTS file, for better performances.</sub>

**Comment by akashlevy** [comment]
Not sure when it started, I just installed it yesterday. I fixed it for my purposes by removing the checksum, but maybe check if you're doing the checksum correctly?

**Comment by akashlevy** [comment]
And I need the Adblock version in particular since I want the links to be removed in the page source.

**Comment by eladkarako** [comment]
I'll comment-out the checksum, for now,  'till I'll figure it out.
(probably the extra space I've added for straightening).

<hr/>
p.s. #2
for hiding the links: <code>hosts_adblock_anti_annoyances_hide.txt</code>
for stopping loading/window popups/browsing: <code>hosts_adblock_anti_annoyances_block.txt</code> + <code>hosts_adblock.txt</code>.

links hiding will remove them from the page using rules like:
a[href*="www.badlink"]  or [src*="www.badlink"] for a image-link
