### ISSUE TITLE
Whitelist requests for Amazon AWS

### ISSUE THREAD

**Issue by WaLLy3K** [eladkarako/hosts.eladkarako.com#2]
Hi Elad, could I ask that you please unblock these sites?

```
s3-1-w.amazonaws.com
s3-1.amazonaws.com
s3-2-w.amazonaws.com
s3-eu-west-1.amazonaws.com
s3-us-west-1.amazonaws.com
s3-us-west-2.amazonaws.com
s3.amazonaws.com
```

Thanks!

**Comment by eladkarako** [comment]
<sub>won't be fixed right now. feel free to fork it, <br/>and remove them on your fork. <br/>you can also exclude specific rules on AdAway (Android) <br/>or use the <code>@@</code> rule for adblock compatible clients.Sorry <sub><em>(not really..)</em></sub></sub>
