### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by BBcan177** [eladkarako/hosts.eladkarako.com#2]
Found the following invalid domains:

admin
bc.geocities.
ea.pixmania.
fi
icaro-consulting.com.
track.zalando.
www..clktag.com
www.166.62.89.103.
www.46.32.240.35.

**Comment by eladkarako** [comment]
You are awesome!
thank you very much!

**Comment by eladkarako** [comment]
ps. I've added this pattern of "bad format" to be inspected by the new (NodeJS) generator,
the first build (for a long time) is now fully generated, and available for free download :]

**Comment by BBcan177** [comment]
Thanks, just one left :)

Line: 431857 
www .. clktag.com

**Comment by eladkarako** [comment]
fixed!
<img alt="" src="https://i.imgur.com/iVvbaAh.gif"/>
<sub>by the way, how you've come across it? I can't imagine you've walked-through all of the list   :)</sub>
<sub>- any sort of program that checks compatibility?</sub>

**Comment by BBcan177** [comment]
Yes I manually tested each line :)

pfBlockerNG:
https://forum.pfsense.org/index.php?topic=102470.0

ps: Would be great to have a compressed archive since the file is so large...

**Comment by eladkarako** [comment]
I did in-fact build archives before, but I rewrote it away, to make the repository slim and responsive.
the hosts file is huge, due to inclusion of many sub-domains for each host, there isn't a way around it since HOSTS-file logic is quite simple <sub>sorrrrrrryyyy....  :/</sub>
